/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.toedter.calendar.JCalendar;
import controller.EmployeeController;
import extra.Extra;
import extra.LengthRestrictedDocument;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import static java.lang.Thread.sleep;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Employee;

/**
 *
 * @author CM <2222cm@gmail.com>
 */
public class Employees extends javax.swing.JDialog {

    private EmployeeController employeeController;
    private DefaultTableModel tableModel;
    private SimpleDateFormat dateFormat;
    private ArrayList<Employee> employeesList;
    private int mode;
    private boolean nameFlag, nicFlag, addressFlag, salaryFlag, mobileFlag, phoneFlag, joinedDateFlag;
    private String lastID = "";

    /**
     * Creates new form EmployeesForm
     */
    public Employees(java.awt.Frame parent, boolean modal) {
        super(parent, modal);;

        initComponents();
        setLocationRelativeTo(null);

        employeesTable.getTableHeader().setReorderingAllowed(false);
        tableModel = (DefaultTableModel) employeesTable.getModel();
        dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        employeesList = new ArrayList<>();

        setFieldLengths();
        setFieldsPanel(false);
        setCalendar(joinedDateText.getJCalendar());
        setCalendar(dobText.getJCalendar());
        viewAllButtonActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeButton = new javax.swing.JButton();
        searchPanel = new javax.swing.JPanel();
        searchText = new javax.swing.JTextField();
        searchCombo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        viewAllButton = new javax.swing.JButton();
        tablePane = new javax.swing.JScrollPane();
        employeesTable = new javax.swing.JTable();
        fieldsPanel = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        idLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nicNoLabel = new javax.swing.JLabel();
        dobLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        mobileLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        joinedDateLabel = new javax.swing.JLabel();
        noteLabel = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        nicNoText = new javax.swing.JTextField();
        addressText = new javax.swing.JTextField();
        mobileText = new javax.swing.JTextField();
        phoneText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        notesText = new javax.swing.JTextArea();
        cancelButton = new javax.swing.JButton();
        salaryLabel = new javax.swing.JLabel();
        salaryText = new javax.swing.JTextField();
        joinedDateText = new com.toedter.calendar.JDateChooser();
        fieldsInfoLabel = new javax.swing.JLabel();
        dobText = new com.toedter.calendar.JDateChooser();
        deleteButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        newButton = new javax.swing.JButton();
        mainInfoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Employees");
        setResizable(false);

        homeButton.setText("Home");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        searchPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(150, 150, 150), 1, true));

        searchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextActionPerformed(evt);
            }
        });

        searchCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ID", "Name", "NIC No" }));
        searchCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchComboActionPerformed(evt);
            }
        });

        jLabel1.setText("Search by");

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        viewAllButton.setText("View All");
        viewAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 298, Short.MAX_VALUE)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(searchCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton)
                    .addComponent(viewAllButton))
                .addContainerGap())
        );

        tablePane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        employeesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "NIC No", "DoB", "Address", "Salary", "Mobile", "Phone", "Joined Date", "Note"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        employeesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeesTableMouseClicked(evt);
            }
        });
        tablePane.setViewportView(employeesTable);
        employeesTable.getColumnModel().getColumn(0).setMinWidth(60);
        employeesTable.getColumnModel().getColumn(0).setMaxWidth(60);
        employeesTable.getColumnModel().getColumn(2).setMinWidth(90);
        employeesTable.getColumnModel().getColumn(2).setMaxWidth(90);
        employeesTable.getColumnModel().getColumn(3).setMinWidth(90);
        employeesTable.getColumnModel().getColumn(3).setMaxWidth(90);
        employeesTable.getColumnModel().getColumn(5).setMinWidth(65);
        employeesTable.getColumnModel().getColumn(5).setMaxWidth(65);
        employeesTable.getColumnModel().getColumn(6).setMinWidth(90);
        employeesTable.getColumnModel().getColumn(6).setMaxWidth(90);
        employeesTable.getColumnModel().getColumn(7).setMinWidth(90);
        employeesTable.getColumnModel().getColumn(7).setMaxWidth(90);
        employeesTable.getColumnModel().getColumn(8).setMinWidth(95);
        employeesTable.getColumnModel().getColumn(8).setMaxWidth(95);

        fieldsPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(150, 150, 150), 1, true));

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        idLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        idLabel.setText("ID");

        nameLabel.setText("Name");

        nicNoLabel.setText("NIC No");

        dobLabel.setText("Date o Birth");
        dobLabel.setPreferredSize(new java.awt.Dimension(90, 17));

        addressLabel.setText("Address");

        mobileLabel.setText("Mobile");

        phoneLabel.setText("Phone");

        joinedDateLabel.setText("Joined Date");
        joinedDateLabel.setPreferredSize(new java.awt.Dimension(84, 27));

        noteLabel.setText("Note");

        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });

        nicNoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicNoTextActionPerformed(evt);
            }
        });
        nicNoText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nicNoTextKeyTyped(evt);
            }
        });

        addressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTextActionPerformed(evt);
            }
        });

        mobileText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileTextActionPerformed(evt);
            }
        });
        mobileText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mobileTextKeyTyped(evt);
            }
        });

        phoneText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTextActionPerformed(evt);
            }
        });
        phoneText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneTextKeyTyped(evt);
            }
        });

        notesText.setColumns(20);
        notesText.setRows(5);
        jScrollPane1.setViewportView(notesText);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        salaryLabel.setText("Salary");

        salaryText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryTextActionPerformed(evt);
            }
        });
        salaryText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                salaryTextKeyTyped(evt);
            }
        });

        joinedDateText.setDateFormatString("yyyy-MM-dd");
        joinedDateText.setIcon(new ImageIcon("./src/icons/calendar-icon.png"));
        joinedDateText.setMaximumSize(new java.awt.Dimension(2147483, 2147483));
        joinedDateText.setMinSelectableDate(new java.util.Date(-62135785703000L));

        fieldsInfoLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        fieldsInfoLabel.setForeground(new java.awt.Color(253, 47, 47));
        fieldsInfoLabel.setText(" ");
        fieldsInfoLabel.setPreferredSize(new java.awt.Dimension(400, 27));

        dobText.setDateFormatString("yyyy-MM-dd");
        dobText.setIcon(new ImageIcon("./src/icons/calendar-icon.png"));

        javax.swing.GroupLayout fieldsPanelLayout = new javax.swing.GroupLayout(fieldsPanel);
        fieldsPanel.setLayout(fieldsPanelLayout);
        fieldsPanelLayout.setHorizontalGroup(
            fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fieldsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fieldsPanelLayout.createSequentialGroup()
                        .addGroup(fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(fieldsPanelLayout.createSequentialGroup()
                                .addComponent(joinedDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(joinedDateText, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
                            .addGroup(fieldsPanelLayout.createSequentialGroup()
                                .addGroup(fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dobLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mobileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(phoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nicNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addressText, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                    .addComponent(mobileText)
                                    .addComponent(nicNoText)
                                    .addComponent(phoneText, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dobText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(fieldsPanelLayout.createSequentialGroup()
                                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameText))
                            .addGroup(fieldsPanelLayout.createSequentialGroup()
                                .addComponent(salaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salaryText)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fieldsPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fieldsPanelLayout.createSequentialGroup()
                        .addComponent(fieldsInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 289, Short.MAX_VALUE)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        fieldsPanelLayout.setVerticalGroup(
            fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fieldsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idLabel)
                .addGap(18, 18, 18)
                .addGroup(fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noteLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fieldsPanelLayout.createSequentialGroup()
                        .addGroup(fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nicNoLabel)
                            .addComponent(nicNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dobText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dobLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addressLabel)
                            .addComponent(addressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salaryLabel)
                            .addComponent(salaryText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mobileLabel)
                            .addComponent(mobileText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneLabel)
                            .addComponent(phoneText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(joinedDateText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(joinedDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(cancelButton)
                    .addComponent(fieldsInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        deleteButton.setText("Delete");
        deleteButton.setPreferredSize(new java.awt.Dimension(90, 29));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        newButton.setText("New");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        mainInfoLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        mainInfoLabel.setText(" ");
        mainInfoLabel.setPreferredSize(new java.awt.Dimension(400, 27));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(mainInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(newButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tablePane, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fieldsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tablePane, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeButton)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editButton)
                    .addComponent(newButton)
                    .addComponent(mainInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    private void viewAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllButtonActionPerformed
        clearFieldsPanel();
        setFieldsPanel(false);
        employeeController = new EmployeeController();

        try {
            employeesList = employeeController.getAllEmployees();
        } catch (SQLException ex) {
            Logger.getLogger(Employees.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Employees.class.getName()).log(Level.SEVERE, null, ex);
        }
        setTable();
        searchText.setText("");
        searchCombo.setSelectedIndex(0);
    }//GEN-LAST:event_viewAllButtonActionPerformed

    private void searchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextActionPerformed
        clearFieldsPanel();
        setFieldsPanel(false);
        String key = "", type = "";
        if (!searchText.getText().equals("")) {
            key = searchText.getText();
            int sel = searchCombo.getSelectedIndex();
            if (sel == 0) {
                type = "id";
            } else if (sel == 1) {
                type = "name";
            } else if (sel == 2) {
                type = "nic";
            }

            try {
                employeesList = employeeController.searchEmployee(key, type);
                setTable();
            } catch (SQLException ex) {
                Logger.getLogger(Employees.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Employees.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            viewAllButtonActionPerformed(null);
        }
    }//GEN-LAST:event_searchTextActionPerformed

    private void searchComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchComboActionPerformed
        searchText.setText("");
    }//GEN-LAST:event_searchComboActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        searchTextActionPerformed(null);
    }//GEN-LAST:event_searchButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        clearFieldsPanel();
        setFieldsPanel(false);
        mode = 0;
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void employeesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeesTableMouseClicked
        mode = 0;
        if (evt.getClickCount() == 1) {
            clearFieldsPanel();
            setFieldsPanel(false);
        } else if (evt.getClickCount() == 2) {
            mode = 1;
            setFieldsPanel(true);
            JTable target = (JTable) evt.getSource();
            setFieldValues(target.getSelectedRow());
        }
    }//GEN-LAST:event_employeesTableMouseClicked

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        clearFieldsPanel();
        setFieldsPanel(false);
        mode = 1;
        if (employeesTable.getSelectedRow() != -1) {
            setFieldsPanel(true);
            setFieldValues(employeesTable.getSelectedRow());
            nameText.requestFocus();
        } else {
            showMainMessage("Select an employee first");
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        mode = 2;
        viewAllButtonActionPerformed(null);
        String newID = new Extra().getNextID(lastID);

        clearFieldsPanel();
        setFieldsPanel(true);
        idLabel.setText(newID);
        nameText.requestFocus();
    }//GEN-LAST:event_newButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        Employee emp = setEmployee();

        if (!nameFlag) {
            showFieldsPanelMessage("Enter a name");
            nameText.requestFocus();
        } else if (!nicFlag) {
            showFieldsPanelMessage("Enter a valid NIC number");
            nicNoText.requestFocus();
        } else if (!addressFlag) {
            showFieldsPanelMessage("Enter an address");
            addressText.requestFocus();
        } else if (!salaryFlag) {
            showFieldsPanelMessage("Enter a salary");
            salaryText.requestFocus();
        } else if (!mobileFlag) {
            showFieldsPanelMessage("Enter a valid mobile number");
            mobileText.requestFocus();
        } else if (!phoneFlag) {
            showFieldsPanelMessage("Enter a valid phone number");
            phoneText.requestFocus();
        } else if (!joinedDateFlag) {
            showFieldsPanelMessage("Enter joined date");
            joinedDateText.requestFocus();
        } else {
            employeeController = new EmployeeController();

            if (mode == 1) {
                boolean updated = false;
                try {
                    updated = employeeController.updateEmployee(emp);
                } catch (SQLException ex) {
                    Logger.getLogger(Employees.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Employees.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (updated) {
                    showMainMessage("Emplyee updated successfully");
                    clearFieldsPanel();
                    setFieldsPanel(false);
                    viewAllButtonActionPerformed(null);
                } else {
                    showMainMessage("Emplyee was not updated");
                }
            } else if (mode == 2) {
                boolean added = false;
                try {
                    added = employeeController.addEmployee(emp);
                } catch (SQLException ex) {
                    Logger.getLogger(Employees.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Employees.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (added) {
                    showMainMessage("New emplyee added successfully");
                    clearFieldsPanel();
                    setFieldsPanel(false);
                    viewAllButtonActionPerformed(null);
                } else {
                    showMainMessage("New emplyee was not added");
                }
            }
        }
        setFlags(false);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        nicNoText.requestFocus();
    }//GEN-LAST:event_nameTextActionPerformed

    private void nicNoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicNoTextActionPerformed
        dobText.requestFocus();
    }//GEN-LAST:event_nicNoTextActionPerformed

    private void addressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTextActionPerformed
        salaryText.requestFocus();
    }//GEN-LAST:event_addressTextActionPerformed

    private void salaryTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryTextActionPerformed
        mobileText.requestFocus();
    }//GEN-LAST:event_salaryTextActionPerformed

    private void mobileTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileTextActionPerformed
        phoneText.requestFocus();
    }//GEN-LAST:event_mobileTextActionPerformed

    private void phoneTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTextActionPerformed
        saveButton.requestFocus();
    }//GEN-LAST:event_phoneTextActionPerformed

    private void nicNoTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicNoTextKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_nicNoTextKeyTyped

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        clearFieldsPanel();
        setFieldsPanel(false);
        boolean deleted = false;
        if (employeesTable.getSelectedRow() != -1) {
            int confirmation = JOptionPane.showConfirmDialog(null, "Delete selected employee?", "Confirm", JOptionPane.YES_NO_OPTION);
            if (confirmation == 0) {
                employeeController = new EmployeeController();
                String id = (String) employeesTable.getValueAt(employeesTable.getSelectedRow(), 0);

                try {
                    deleted = employeeController.deleteEmployee(id);
                } catch (SQLException ex) {
                    Logger.getLogger(Employees.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Employees.class.getName()).log(Level.SEVERE, null, ex);
                }

                if (deleted) {
                    showMainMessage("'" + id + "' has been deleted");
                    viewAllButtonActionPerformed(null);
                } else {
                    showMainMessage("Employee has not been deleted");
                }
            }
        } else {
            showMainMessage("Select an employee first");
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void salaryTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salaryTextKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_PERIOD))) {
            evt.consume();
        }
    }//GEN-LAST:event_salaryTextKeyTyped

    private void mobileTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobileTextKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_mobileTextKeyTyped

    private void phoneTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneTextKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_phoneTextKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Employees dialog = new Employees(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressText;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel dobLabel;
    private com.toedter.calendar.JDateChooser dobText;
    private javax.swing.JButton editButton;
    private javax.swing.JTable employeesTable;
    private javax.swing.JLabel fieldsInfoLabel;
    private javax.swing.JPanel fieldsPanel;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel joinedDateLabel;
    private com.toedter.calendar.JDateChooser joinedDateText;
    private javax.swing.JLabel mainInfoLabel;
    private javax.swing.JLabel mobileLabel;
    private javax.swing.JTextField mobileText;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameText;
    private javax.swing.JButton newButton;
    private javax.swing.JLabel nicNoLabel;
    private javax.swing.JTextField nicNoText;
    private javax.swing.JLabel noteLabel;
    private javax.swing.JTextArea notesText;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField phoneText;
    private javax.swing.JLabel salaryLabel;
    private javax.swing.JTextField salaryText;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JComboBox searchCombo;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTextField searchText;
    private javax.swing.JScrollPane tablePane;
    private javax.swing.JButton viewAllButton;
    // End of variables declaration//GEN-END:variables

    private void setCalendar(JCalendar calendar) {
        Dimension size = new Dimension(250, 170);
        calendar.setPreferredSize(size);
        calendar.setWeekOfYearVisible(false);
        calendar.setTodayButtonVisible(true);
    }

    private void setFieldLengths() {
        nicNoText.setDocument(new LengthRestrictedDocument(9));
        mobileText.setDocument(new LengthRestrictedDocument(10));
        phoneText.setDocument(new LengthRestrictedDocument(10));
    }

    private void setTable() {
        tableModel.setRowCount(0);
        if (!employeesList.isEmpty()) {
            int phone;
            for (int i = 0; i < employeesList.size(); i++) {
                Employee emp = employeesList.get(i);
                lastID = emp.getId();
                phone = emp.getPhone();
                if (phone == 0) {
                    Object[] row = {emp.getId(), emp.getName(), emp.getNic() + "", emp.getDob(), emp.getAddress(), emp.getSalary(), "0" + emp.getMobile(), null, emp.getJoinedDate(), emp.getNotes()};
                    tableModel.addRow(row);
                } else {
                    Object[] row = {emp.getId(), emp.getName(), emp.getNic() + "", emp.getDob(), emp.getAddress(), emp.getSalary(), "0" + emp.getMobile(), "0" + emp.getPhone(), emp.getJoinedDate(), emp.getNotes()};
                    tableModel.addRow(row);
                }
            }
        } else {
            showMainMessage("No employees in database");
            lastID = new Extra().getFirstID("employee");
        }
    }

    private void setFieldsPanel(boolean b) {
        idLabel.setEnabled(b);
        nameLabel.setEnabled(b);
        nicNoLabel.setEnabled(b);
        dobLabel.setEnabled(b);
        addressLabel.setEnabled(b);
        salaryLabel.setEnabled(b);
        mobileLabel.setEnabled(b);
        phoneLabel.setEnabled(b);
        joinedDateLabel.setEnabled(b);
        noteLabel.setEnabled(b);

        nameText.setEnabled(b);
        nicNoText.setEnabled(b);
        dobText.setEnabled(b);
        addressText.setEnabled(b);
        salaryText.setEnabled(b);
        mobileText.setEnabled(b);
        phoneText.setEnabled(b);
        joinedDateText.setEnabled(b);
        notesText.setEnabled(b);
        saveButton.setEnabled(b);
        cancelButton.setEnabled(b);
    }

    private void clearFieldsPanel() {
        idLabel.setText("ID");
        nameText.setText("");
        nicNoText.setText("");
        dobText.setDate(null);
        addressText.setText("");
        salaryText.setText("");
        mobileText.setText("");
        phoneText.setText("");
        joinedDateText.setDate(null);
        notesText.setText("");
    }

    private void setFieldValues(int selectedRow) {
        idLabel.setText((String) employeesTable.getValueAt(selectedRow, 0));
        nameText.setText((String) employeesTable.getValueAt(selectedRow, 1));
        nicNoText.setText((String) employeesTable.getValueAt(selectedRow, 2));

        try {
            Date date = dateFormat.parse((String) employeesTable.getValueAt(selectedRow, 3));
            dobText.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(Employees.class.getName()).log(Level.SEVERE, null, ex);
        }

        addressText.setText((String) employeesTable.getValueAt(selectedRow, 4));
        salaryText.setText(employeesTable.getValueAt(selectedRow, 5) + "");
        mobileText.setText(employeesTable.getValueAt(selectedRow, 6) + "");
        if (employeesTable.getValueAt(selectedRow, 7) != null) {
            phoneText.setText(employeesTable.getValueAt(selectedRow, 7) + "");
        }

        try {
            Date date = dateFormat.parse((String) employeesTable.getValueAt(selectedRow, 8));
            joinedDateText.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(Employees.class.getName()).log(Level.SEVERE, null, ex);
        }

        notesText.setText((String) employeesTable.getValueAt(selectedRow, 9));
    }

    private Employee setEmployee() {
        String name = "", dob = "", address = "", joinedDate = "", note = "";
        int nic = 0, mobile = 0, phone = 0;
        double salary = 0;
        Employee em = null;

        if (!nameText.getText().equals("")) {
            nameFlag = true;
            name = nameText.getText();
        }
        if (!nicNoText.getText().equals("")) {
            nic = Integer.parseInt(nicNoText.getText());
            if (new Extra().validateNICNumber(nicNoText)) {
                nicFlag = true;
            }
        }
        if (dobText.getDate() != null) {
            joinedDateFlag = true;
            Date d = dobText.getDate();
            dob = dateFormat.format(d);
        } else {
            dob = "";
        }
        if (!addressText.getText().equals("")) {
            addressFlag = true;
            address = addressText.getText();
        }
        if (!salaryText.getText().equals("")) {
            salaryFlag = true;
            salary = Double.parseDouble(salaryText.getText());
        }
        if (!mobileText.getText().equals("")) {
            if (new Extra().validateMobileNumber(mobileText)) {
                mobileFlag = true;
                mobile = Integer.parseInt(mobileText.getText());
            }
        }
        if (!phoneText.getText().equals("")) {
            if (new Extra().validatePhoneNumber(phoneText)) {
                phoneFlag = true;
                phone = Integer.parseInt(phoneText.getText());
            }
        } else {
            phoneFlag = true;
        }
        if (joinedDateText.getDate() != null) {
            joinedDateFlag = true;
            Date d = joinedDateText.getDate();
            joinedDate = dateFormat.format(d);
        }
        if (!notesText.getText().equals("")) {
            note = notesText.getText();
        }

        em = new Employee(idLabel.getText(), name, nic, dob, address, salary, mobile, phone, joinedDate, note);

        return em;
    }

    private void setFlags(boolean b) {
        nameFlag = b;
        nicFlag = b;
        addressFlag = b;
        salaryFlag = b;
        mobileFlag = b;
        phoneFlag = b;
        joinedDateFlag = b;
    }

    private void showMainMessage(String message) {
        final String msg = message;

        new Thread() {
            public void run() {
                mainInfoLabel.setText("");
                try {
                    sleep(50);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Customers.class.getName()).log(Level.SEVERE, null, ex);
                }

                mainInfoLabel.setText(msg);
                try {
                    sleep(50);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Customers.class.getName()).log(Level.SEVERE, null, ex);
                }
                mainInfoLabel.setText("");
                try {
                    sleep(100);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Customers.class.getName()).log(Level.SEVERE, null, ex);
                }

                mainInfoLabel.setText(msg);

                try {
                    sleep(5000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(CustomerOrder.class.getName()).log(Level.SEVERE, null, ex);
                }

                mainInfoLabel.setText("");
            }
        }.start();
    }

    private void showFieldsPanelMessage(String message) {
        final String msg = message;

        new Thread() {
            public void run() {
                fieldsInfoLabel.setText("");
                try {
                    sleep(50);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Customers.class.getName()).log(Level.SEVERE, null, ex);
                }

                fieldsInfoLabel.setText(msg);
                try {
                    sleep(50);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Customers.class.getName()).log(Level.SEVERE, null, ex);
                }
                fieldsInfoLabel.setText("");
                try {
                    sleep(100);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Customers.class.getName()).log(Level.SEVERE, null, ex);
                }

                fieldsInfoLabel.setText(msg);

                try {
                    sleep(5000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(CustomerOrder.class.getName()).log(Level.SEVERE, null, ex);
                }

                fieldsInfoLabel.setText("");
            }
        }.start();
    }
}
